### ISSUE TITLE
Invalid view holder adapter 

### ISSUE THREAD

**Issue by kamilwlf** [blipinsk/RecyclerViewHeader#2]
Uruchomiłem działa bez problemów, ale raz dostałem wyjątek:
```ava.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{4160d8a0 position=8 id=-1, oldPos=-1, pLpos:-1undefined adapter position no parent}
            at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:3498)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3628)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3609)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1859)
            at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:356)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1274)```

Mój RecyclerView to `GridLayoutManager`

cały kod:
http://paste.ofcode.org/KWLaB5U4nWZFCDCaZytz3q

**Comment by blipinsk** [comment]
Błąd zgłoszony jako problem z `RecyclerView`.
https://code.google.com/p/android/issues/detail?id=77846
https://code.google.com/p/android/issues/detail?id=77232

**Comment by kamilwlf** [comment]
masz jakieś sugestie jak tego uniknąć?

**Comment by jjhesk** [comment]
@blipinsk  how did you fix this issue?? I had the [same issue](https://github.com/cymcsg/UltimateRecyclerView/issues/135)

**Comment by blipinsk** [comment]
I didn't fix the issue since it wasn't my issue. It has been reported as a bug inside `RecyclerView` itself:

https://code.google.com/p/android/issues/detail?id=77846
https://code.google.com/p/android/issues/detail?id=77232

**Comment by Nodrex** [comment]
Ok i solved this problem by Overriding android.support.v7.widget.LinearLayoutManager method onLayoutChildren like this : 

public void onLayoutChildren(Recycler arg0, State arg1) {
	try {
		super.onLayoutChildren(arg0, arg1);
	} catch (Exception e) {
		Util.log("onLayoutChildren :" + e.toString());
	}
}

**Comment by arifNislam** [comment]
@Nodrex Do you know, exactly why this situation arise?
