### ISSUE TITLE
Use this library to add Recyclerview head. Generating a crash...

### ISSUE THREAD

**Issue by congwiny** [blipinsk/RecyclerViewHeader#24]
Use this library to add Recyclerview head. Generating a crash when using two fingers simultaneously press the screen and slide up and down the list of two fingers simultaneously.
The following is a crash log：
java.lang.IllegalArgumentException: pointerIndex out of range
 at android.view.MotionEvent.nativeGetPointerId(Native Method)
 at android.view.MotionEvent.getPointerId(MotionEvent.java:2061)
 at android.support.v4.view.MotionEventCompatEclair.getPointerId(MotionEventCompatEclair.java:29)
 at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getPointerId(MotionEventCompat.java:106)
 at android.support.v4.view.MotionEventCompat.getPointerId(MotionEventCompat.java:453)
 at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:1734)
 at com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView.onTouchEvent(ObservableRecyclerView.java:256)
 at com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader.onTouchEvent(RecyclerViewHeader.java:237)
 at android.view.View.dispatchTouchEvent(View.java:9010)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2672)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2384)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2715)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2552)
 at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1767)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2840)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2513)
 at android.view.View.dispatchPointerEvent(View.java:9228)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4665)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4503)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4053)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4106)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4072)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4186)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4080)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4243)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4053)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4106)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4072)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4080)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4053)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6513)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6412)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6383)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6603)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:143)
 at android.os.Looper.loop(Looper.java:130)
 at android.app.ActivityThread.main(ActivityThread.java:5834)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by blipinsk** [comment]
I don't think it's a bug in my code. Nothing gets thrown if I try to reproduce this issue. Check if it happens as well if you try to use a normal `RecyclerView` instead of `com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView`.

**Comment by blipinsk** [comment]
@congwiny Any update on the issue? Did it happen when you were using a regular `RecyclerView`?

**Comment by congwiny** [comment]
Thank you,I will try to use a normal RecyclerView.
