### ISSUE TITLE
Illegal Argument Exception RecyclerViewHeader.java 237

### ISSUE THREAD

**Issue by cazador4** [blipinsk/RecyclerViewHeader#37]
```
java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetPointerId(Native Method)
	at android.view.MotionEvent.getPointerId(MotionEvent.java:1934)
	at android.support.v4.view.MotionEventCompatEclair.getPointerId(MotionEventCompatEclair.java:29)
	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getPointerId(MotionEventCompat.java:106)
	at android.support.v4.view.MotionEventCompat.getPointerId(MotionEventCompat.java:453)
	at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:1917)
	at com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader.onTouchEvent(RecyclerViewHeader.java:237)
	at android.view.View.dispatchTouchEvent(View.java:7782)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2316)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2013)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2350)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2109)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1541)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2491)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2057)
	at android.view.View.dispatchPointerEvent(View.java:7973)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4411)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4282)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3954)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4011)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3847)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3855)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3828)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6160)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6123)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6077)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6305)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:138)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by blipinsk** [comment]
Hi, when does this happen? What layout do you set for your header?

**Comment by cazador4** [comment]
Hi, I can't reproduce this exception :( . We have splunk on the project and I can see it there but it took place in one user cellphone.

We are using LinearLayout in a resource xml file. 
We doing first this: header = RecyclerViewHeader.fromXml(getActivity(), R.layout.user_header_view);
then header.attachTo(mRecyclerView);

If you need more information, please ask me. 

Thanks!

**Comment by blipinsk** [comment]
There was something similar a while ago (issue #24), but I was suspecting the external library to be the source of the issue. Maybe it wasn't... Can you try to scrolling by touching the header with two fingers simultaneously?

**Comment by cazador4** [comment]
I did it but nothings happened. It's working well. I can't reproduce the bug :(
By the way, we have only one exception like this... If it appears again, i will re open this. 
Are you ok with this?

**Comment by blipinsk** [comment]
Yep sure :+1:
