### ISSUE TITLE
i find a crash bug

### ISSUE THREAD

**Issue by danjianhua** [blipinsk/RecyclerViewHeader#54]
java.lang.IllegalArgumentException
pointerIndex out of range
android.view.MotionEvent.nativeGetPointerId(Native Method)
android.view.MotionEvent.getPointerId(MotionEvent.java:1969)
android.support.v4.view.MotionEventCompatEclair.getPointerId(MotionEventCompatEclair.java:29)
android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getPointerId(MotionEventCompat.java:112)
android.support.v4.view.MotionEventCompat.getPointerId(MotionEventCompat.java:487)
android.support.v7.widget.RecyclerView.onPointerUp(RecyclerView.java:2704)
android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2659)
**com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader$RecyclerViewDelegate.onTouchEvent(RecyclerViewHeader.java:327)**
com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader.onTouchEvent(RecyclerViewHeader.java:183)
android.view.View.dispatchTouchEvent(View.java:8593)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2524)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2157)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2530)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2530)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2530)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2530)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2530)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2545)
com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1818)
com.mit.dstore.app.BaseActivity.dispatchTouchEvent(BaseActivity.java:206)
com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2483)
android.view.View.dispatchPointerEvent(View.java:8799)
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4817)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4632)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4124)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4183)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4143)
android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4286)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4151)
android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4343)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4124)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4183)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4143)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4151)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4124)
android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6645)
android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6619)
android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6572)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6804)
android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:216)
android.os.MessageQueue.nativePollOnce(Native Method)
android.os.MessageQueue.next(MessageQueue.java:153)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:5809)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

hople your fix it
   thanks

**Comment by blipinsk** [comment]
Hi, which version of Support Library are you using?

**Comment by danjianhua** [comment]
compile 'com.bartoszlipinski:recyclerviewheader2:2.0.1'

I use this version
tks

**Comment by blipinsk** [comment]
but which version of **Support Library** (`compile 'com.android.support:recyclerview-v7:XX.X.X`)?

**Comment by danjianhua** [comment]
compile 'com.android.support:recyclerview-v7:23.4.0'

I user the Library

**Comment by danjianhua** [comment]
**some xml file** 
<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <com.wuxiaolong.pullloadmorerecyclerview.PullLoadMoreRecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center_horizontal|top"/>
        <com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader
            android:id="@+id/header"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal|top">
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">
            <com.midt.sotore.ui.stub.SlideShowView
                android:id="@+id/slideshowView"
                android:layout_width="match_parent"
                android:layout_height="168dp"
                android:background="@drawable/gray_long"/>
            <GridView
                android:id="@+id/grid_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                android:numColumns="4"
                android:listSelector="@android:color/transparent"
                android:columnWidth="5dp"
                android:paddingBottom="5dp"></GridView>

                <View
                    android:layout_width="match_parent"
                    android:layout_height="10dp"/>
            </LinearLayout>
        </com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader>
    </FrameLayout>

**some java code**
    @Bind(R.id.recycler_view)
    PullLoadMoreRecyclerView recyclerView;
    @Bind(R.id.header)
    RecyclerViewHeader headerView;

     headerView.attachTo(recyclerView.getRecyclerView());


Hope it can help you

**Comment by blipinsk** [comment]
`SlideShowView` what does it do?
does it use like a pinch to zoom mechanism?

**Comment by faziltm** [comment]
@blipinsk Same problem effected for me also.
My error is

E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetPointerId(Native Method)
at android.view.MotionEvent.getPointerId(MotionEvent.java:1938)
at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2783)
at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader$RecyclerViewDelegate.onTouchEvent(RecyclerViewHeader.java:327)
at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader.onTouchEvent(RecyclerViewHeader.java:183)
at android.view.View.dispatchTouchEvent(View.java:8393)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2426)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
at android.app.Activity.dispatchTouchEvent(Activity.java:2749)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
at android.view.View.dispatchPointerEvent(View.java:8583)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4091)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3957)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3562)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3528)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3638)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3536)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3695)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3562)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3528)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3536)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5806)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5745)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5716)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5896)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
at android.os.MessageQ
Shutting down VM
FATAL EXCEPTION: main
Process: com.ecom.ecom1, PID: 12415
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetPointerId(Native Method)
at android.view.MotionEvent.getPointerId(MotionEvent.java:1938)
at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2783)
at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader$RecyclerViewDelegate.onTouchEvent(RecyclerViewHeader.java:327)
at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader.onTouchEvent(RecyclerViewHeader.java:183)
at android.view.View.dispatchTouchEvent(View.java:8393)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2426)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
at android.app.Activity.dispatchTouchEvent(Activity.java:2749)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
at android.view.View.dispatchPointerEvent(View.java:8583)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4091)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3957)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3562)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3528)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3638)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3536)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3695)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3562)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3528)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3536)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3509)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5806)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5745)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5716)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5896)
at android.view.InputEventReceiver.dispatchInputEv


When pinch to header(Recyclerview header) to Recyleview element. It shows this error. I never used pinch mechanism. How to solve it. please help me.

**Comment by blipinsk** [comment]
Please read the [`Limitations` section](https://github.com/blipinsk/RecyclerViewHeader#limitations)

> No complicated touch system (including scrollable elements)
