### ISSUE TITLE
IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by baofei** [blipinsk/RecyclerViewHeader#66]
Multi-touch zoom happens bug

java.lang.IllegalArgumentException: pointerIndex out of range
                                                                                                    at android.view.MotionEvent.nativeGetPointerId(Native Method)
                                                                                                    at android.view.MotionEvent.getPointerId(MotionEvent.java:1969)
                                                                                                    at android.support.v4.view.MotionEventCompatEclair.getPointerId(MotionEventCompatEclair.java:29)
                                                                                                    at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getPointerId(MotionEventCompat.java:106)
                                                                                                    at android.support.v4.view.MotionEventCompat.getPointerId(MotionEventCompat.java:453)
                                                                                                    at android.support.v7.widget.RecyclerView.onPointerUp(RecyclerView.java:2541)
                                                                                                    at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2496)
                                                                                                    at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader$RecyclerViewDelegate.onTouchEvent(RecyclerViewHeader.java:333)
                                                                                                    at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader.onTouchEvent(RecyclerViewHeader.java:189)
                                                                                                    at android.view.View.dispatchTouchEvent(View.java:8476)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
                                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                                                    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2752)
                                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                                                    at android.view.View.dispatchPointerEvent(View.java:8671)
                                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193)
                                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059)
                                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740)
                                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797)
                                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
                                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
                                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
                                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
                                                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912)
                                                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851)
                                                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822)
                                                                                                    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6002)
                                                                                                    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                                                    at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    at android.os.MessageQueue.next(MessageQueue.java:143)
                                                                                                    at android.os.Looper.loop(Looper.java:122)
                                                                                                	at android.app.ActivityThread.m

**Comment by blipinsk** [comment]
Please read the [`Limitations` section](https://github.com/blipinsk/RecyclerViewHeader#limitations)

> No complicated touch system (including scrollable elements)
