### ISSUE TITLE
NullPointerException after detach()

### ISSUE THREAD

**Issue by mateuszs7** [blipinsk/RecyclerViewHeader#73]
After calling detach() method on header I get NullPointerException
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader$LayoutManagerDelegate.isReversed()' on a null object reference
                      at com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader$HeaderItemDecoration.getItemOffsets(RecyclerViewHeader.java:218)
                      at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:4670)
                      at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8752)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1582)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:575)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                      at android.view.View.layout(View.java:15520)
                      at android.view.ViewGroup.layout(ViewGroup.java:4870)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2128)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1882)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1087)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6040)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:606)
                      at android.view.Choreographer.doFrame(Choreographer.java:575)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
```

**Comment by Rohitsachdeva** [comment]
pls answer this

**Comment by Rohitsachdeva** [comment]
i have fixed this bug by reload fragment

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
